[platformio]
src_dir = firmware/waterbox
lib_dir = libraries

[env:microduino_coreplus]
platform = atmelavr
board = 644pa16m
framework = arduino
lib_ignore = ArduinoJson, TimeAlarms
monitor_speed = 19200
