[platformio]
src_dir = firmware/waterbox
lib_dir = libraries
default_envs = 644pa16m

[env:644pa16m]
platform = atmelavr
board = 644pa8m
framework = arduino
lib_ldf_mode = deep+
lib_ignore = ArduinoJson, TimeAlarms
monitor_speed = 57600
upload_protocol = arduino
upload_speed = 57600
