name=GSMPubSubClient
version=2.7.0
author=Nick O'Leary
maintainer=2GWaterMeter
sentence=MQTT client using sim800Client instead of Ethernet
paragraph=Fork of PubSubClient bound to SIM800 transparent TCP.
category=Communication
url=http://knolleary.net
architectures=*
depends=sim800
includes=GSMPubSubClient.h
